name: gtex
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=3.2.0
    - r-irkernel=1.1
    - r-devtools
    - r-rmarkdown=0.7
    - r-knitr
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-stringr
    - r-forcats
    - r-cowplot
    - r-scales
    - r-lubridate