channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base==4.1.2
    - r-knitr
    - r-rmarkdown
    - r-devtools
    - r-tidyverse
    - r-cowplot
    - r-magick
    - r-biocmanager
    - bioconductor-recount3
    - bioconductor-biomart
    - bioconductor-deseq2