name: gtex
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.1.2
    - r-knitr
    - r-rmarkdown
    - r-devtools
    - r-devtools
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-readr
    - r-vroom
    - r-purrr
    - r-tibble
    - r-stringr
    - r-forcats
    - r-cowplot
    - r-magick
