channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base==4.1.2
    - r-tidyverse
    - r-rtsne
    - r-cowplot
    - r-ggubbr
    - r-magick
    - bioconductor-recount3
    - bioconductor-biomart
    - bioconductor-deseq2
