channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.1.2
    - r-knitr
    - r-rmarkdown
    - r-irkernel=1.3
    - r-devtools
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-readr
    - r-purrr
    - r-tibble
    - r-stringr
    - r-forcats
    - r-rtsne
    - r-cowplot
    - r-ggpubr
    - r-magick
    - r-rcpp
    - bioconductor-recount3
    - bioconductor-biomart
    - bioconductor-deseq2
